app:
    name: blog
httpd:
    port: "8888"
    host: 'localhost'
swagger:
    host: 'art-frela.ru'
database:
    url: 'mongodb://elk-01.watcom.local:27017'
    name: blog

env: develop
log:
    level: debug
    file: