// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Comments", testComments)
	t.Run("Posts", testPosts)
	t.Run("Rubrics", testRubrics)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("Comments", testCommentsDelete)
	t.Run("Posts", testPostsDelete)
	t.Run("Rubrics", testRubricsDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Comments", testCommentsQueryDeleteAll)
	t.Run("Posts", testPostsQueryDeleteAll)
	t.Run("Rubrics", testRubricsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Comments", testCommentsSliceDeleteAll)
	t.Run("Posts", testPostsSliceDeleteAll)
	t.Run("Rubrics", testRubricsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Comments", testCommentsExists)
	t.Run("Posts", testPostsExists)
	t.Run("Rubrics", testRubricsExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("Comments", testCommentsFind)
	t.Run("Posts", testPostsFind)
	t.Run("Rubrics", testRubricsFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("Comments", testCommentsBind)
	t.Run("Posts", testPostsBind)
	t.Run("Rubrics", testRubricsBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("Comments", testCommentsOne)
	t.Run("Posts", testPostsOne)
	t.Run("Rubrics", testRubricsOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("Comments", testCommentsAll)
	t.Run("Posts", testPostsAll)
	t.Run("Rubrics", testRubricsAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("Comments", testCommentsCount)
	t.Run("Posts", testPostsCount)
	t.Run("Rubrics", testRubricsCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Comments", testCommentsHooks)
	t.Run("Posts", testPostsHooks)
	t.Run("Rubrics", testRubricsHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Comments", testCommentsInsert)
	t.Run("Comments", testCommentsInsertWhitelist)
	t.Run("Posts", testPostsInsert)
	t.Run("Posts", testPostsInsertWhitelist)
	t.Run("Rubrics", testRubricsInsert)
	t.Run("Rubrics", testRubricsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("CommentToPostUsingPost", testCommentToOnePostUsingPost)
	t.Run("CommentToUserUsingAuthor", testCommentToOneUserUsingAuthor)
	t.Run("PostToRubricUsingRubric", testPostToOneRubricUsingRubric)
	t.Run("PostToUserUsingAuthor", testPostToOneUserUsingAuthor)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("PostToComments", testPostToManyComments)
	t.Run("RubricToPosts", testRubricToManyPosts)
	t.Run("UserToAuthorComments", testUserToManyAuthorComments)
	t.Run("UserToAuthorPosts", testUserToManyAuthorPosts)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("CommentToPostUsingComments", testCommentToOneSetOpPostUsingPost)
	t.Run("CommentToUserUsingAuthorComments", testCommentToOneSetOpUserUsingAuthor)
	t.Run("PostToRubricUsingPosts", testPostToOneSetOpRubricUsingRubric)
	t.Run("PostToUserUsingAuthorPosts", testPostToOneSetOpUserUsingAuthor)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("CommentToUserUsingAuthorComments", testCommentToOneRemoveOpUserUsingAuthor)
	t.Run("PostToRubricUsingPosts", testPostToOneRemoveOpRubricUsingRubric)
	t.Run("PostToUserUsingAuthorPosts", testPostToOneRemoveOpUserUsingAuthor)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("PostToComments", testPostToManyAddOpComments)
	t.Run("RubricToPosts", testRubricToManyAddOpPosts)
	t.Run("UserToAuthorComments", testUserToManyAddOpAuthorComments)
	t.Run("UserToAuthorPosts", testUserToManyAddOpAuthorPosts)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("RubricToPosts", testRubricToManySetOpPosts)
	t.Run("UserToAuthorComments", testUserToManySetOpAuthorComments)
	t.Run("UserToAuthorPosts", testUserToManySetOpAuthorPosts)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("RubricToPosts", testRubricToManyRemoveOpPosts)
	t.Run("UserToAuthorComments", testUserToManyRemoveOpAuthorComments)
	t.Run("UserToAuthorPosts", testUserToManyRemoveOpAuthorPosts)
}

func TestReload(t *testing.T) {
	t.Run("Comments", testCommentsReload)
	t.Run("Posts", testPostsReload)
	t.Run("Rubrics", testRubricsReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Comments", testCommentsReloadAll)
	t.Run("Posts", testPostsReloadAll)
	t.Run("Rubrics", testRubricsReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Comments", testCommentsSelect)
	t.Run("Posts", testPostsSelect)
	t.Run("Rubrics", testRubricsSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Comments", testCommentsUpdate)
	t.Run("Posts", testPostsUpdate)
	t.Run("Rubrics", testRubricsUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Comments", testCommentsSliceUpdateAll)
	t.Run("Posts", testPostsSliceUpdateAll)
	t.Run("Rubrics", testRubricsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
