// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRubrics(t *testing.T) {
	t.Parallel()

	query := Rubrics()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRubricsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Rubric{}
	if err = randomize.Struct(seed, o, rubricDBTypes, true, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Rubrics().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRubricsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Rubric{}
	if err = randomize.Struct(seed, o, rubricDBTypes, true, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Rubrics().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Rubrics().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRubricsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Rubric{}
	if err = randomize.Struct(seed, o, rubricDBTypes, true, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RubricSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Rubrics().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRubricsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Rubric{}
	if err = randomize.Struct(seed, o, rubricDBTypes, true, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RubricExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Rubric exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RubricExists to return true, but got false.")
	}
}

func testRubricsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Rubric{}
	if err = randomize.Struct(seed, o, rubricDBTypes, true, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	rubricFound, err := FindRubric(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if rubricFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRubricsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Rubric{}
	if err = randomize.Struct(seed, o, rubricDBTypes, true, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Rubrics().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRubricsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Rubric{}
	if err = randomize.Struct(seed, o, rubricDBTypes, true, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Rubrics().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRubricsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	rubricOne := &Rubric{}
	rubricTwo := &Rubric{}
	if err = randomize.Struct(seed, rubricOne, rubricDBTypes, false, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}
	if err = randomize.Struct(seed, rubricTwo, rubricDBTypes, false, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = rubricOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = rubricTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Rubrics().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRubricsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	rubricOne := &Rubric{}
	rubricTwo := &Rubric{}
	if err = randomize.Struct(seed, rubricOne, rubricDBTypes, false, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}
	if err = randomize.Struct(seed, rubricTwo, rubricDBTypes, false, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = rubricOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = rubricTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rubrics().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func rubricBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Rubric) error {
	*o = Rubric{}
	return nil
}

func rubricAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Rubric) error {
	*o = Rubric{}
	return nil
}

func rubricAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Rubric) error {
	*o = Rubric{}
	return nil
}

func rubricBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Rubric) error {
	*o = Rubric{}
	return nil
}

func rubricAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Rubric) error {
	*o = Rubric{}
	return nil
}

func rubricBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Rubric) error {
	*o = Rubric{}
	return nil
}

func rubricAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Rubric) error {
	*o = Rubric{}
	return nil
}

func rubricBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Rubric) error {
	*o = Rubric{}
	return nil
}

func rubricAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Rubric) error {
	*o = Rubric{}
	return nil
}

func testRubricsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Rubric{}
	o := &Rubric{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, rubricDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Rubric object: %s", err)
	}

	AddRubricHook(boil.BeforeInsertHook, rubricBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	rubricBeforeInsertHooks = []RubricHook{}

	AddRubricHook(boil.AfterInsertHook, rubricAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	rubricAfterInsertHooks = []RubricHook{}

	AddRubricHook(boil.AfterSelectHook, rubricAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	rubricAfterSelectHooks = []RubricHook{}

	AddRubricHook(boil.BeforeUpdateHook, rubricBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	rubricBeforeUpdateHooks = []RubricHook{}

	AddRubricHook(boil.AfterUpdateHook, rubricAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	rubricAfterUpdateHooks = []RubricHook{}

	AddRubricHook(boil.BeforeDeleteHook, rubricBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	rubricBeforeDeleteHooks = []RubricHook{}

	AddRubricHook(boil.AfterDeleteHook, rubricAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	rubricAfterDeleteHooks = []RubricHook{}

	AddRubricHook(boil.BeforeUpsertHook, rubricBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	rubricBeforeUpsertHooks = []RubricHook{}

	AddRubricHook(boil.AfterUpsertHook, rubricAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	rubricAfterUpsertHooks = []RubricHook{}
}

func testRubricsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Rubric{}
	if err = randomize.Struct(seed, o, rubricDBTypes, true, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rubrics().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRubricsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Rubric{}
	if err = randomize.Struct(seed, o, rubricDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(rubricColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Rubrics().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRubricToManyPosts(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Rubric
	var b, c Post

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, rubricDBTypes, true, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, postDBTypes, false, postColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, postDBTypes, false, postColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.RubricID, a.ID)
	queries.Assign(&c.RubricID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Posts().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.RubricID, b.RubricID) {
			bFound = true
		}
		if queries.Equal(v.RubricID, c.RubricID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := RubricSlice{&a}
	if err = a.L.LoadPosts(ctx, tx, false, (*[]*Rubric)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Posts); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Posts = nil
	if err = a.L.LoadPosts(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Posts); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testRubricToManyAddOpPosts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Rubric
	var b, c, d, e Post

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, rubricDBTypes, false, strmangle.SetComplement(rubricPrimaryKeyColumns, rubricColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Post{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, postDBTypes, false, strmangle.SetComplement(postPrimaryKeyColumns, postColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Post{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddPosts(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.RubricID) {
			t.Error("foreign key was wrong value", a.ID, first.RubricID)
		}
		if !queries.Equal(a.ID, second.RubricID) {
			t.Error("foreign key was wrong value", a.ID, second.RubricID)
		}

		if first.R.Rubric != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Rubric != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Posts[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Posts[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Posts().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testRubricToManySetOpPosts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Rubric
	var b, c, d, e Post

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, rubricDBTypes, false, strmangle.SetComplement(rubricPrimaryKeyColumns, rubricColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Post{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, postDBTypes, false, strmangle.SetComplement(postPrimaryKeyColumns, postColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetPosts(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Posts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetPosts(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Posts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.RubricID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.RubricID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.RubricID) {
		t.Error("foreign key was wrong value", a.ID, d.RubricID)
	}
	if !queries.Equal(a.ID, e.RubricID) {
		t.Error("foreign key was wrong value", a.ID, e.RubricID)
	}

	if b.R.Rubric != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Rubric != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Rubric != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Rubric != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.Posts[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Posts[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testRubricToManyRemoveOpPosts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Rubric
	var b, c, d, e Post

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, rubricDBTypes, false, strmangle.SetComplement(rubricPrimaryKeyColumns, rubricColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Post{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, postDBTypes, false, strmangle.SetComplement(postPrimaryKeyColumns, postColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddPosts(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Posts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemovePosts(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Posts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.RubricID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.RubricID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Rubric != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Rubric != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Rubric != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Rubric != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.Posts) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Posts[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Posts[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testRubricsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Rubric{}
	if err = randomize.Struct(seed, o, rubricDBTypes, true, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRubricsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Rubric{}
	if err = randomize.Struct(seed, o, rubricDBTypes, true, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RubricSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRubricsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Rubric{}
	if err = randomize.Struct(seed, o, rubricDBTypes, true, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Rubrics().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	rubricDBTypes = map[string]string{`ID`: `varchar`, `Title`: `varchar`, `Description`: `text`}
	_             = bytes.MinRead
)

func testRubricsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(rubricPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(rubricAllColumns) == len(rubricPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Rubric{}
	if err = randomize.Struct(seed, o, rubricDBTypes, true, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rubrics().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, rubricDBTypes, true, rubricPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRubricsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(rubricAllColumns) == len(rubricPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Rubric{}
	if err = randomize.Struct(seed, o, rubricDBTypes, true, rubricColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rubrics().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, rubricDBTypes, true, rubricPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(rubricAllColumns, rubricPrimaryKeyColumns) {
		fields = rubricAllColumns
	} else {
		fields = strmangle.SetComplement(
			rubricAllColumns,
			rubricPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RubricSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRubricsUpsert(t *testing.T) {
	t.Parallel()

	if len(rubricAllColumns) == len(rubricPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLRubricUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Rubric{}
	if err = randomize.Struct(seed, &o, rubricDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Rubric: %s", err)
	}

	count, err := Rubrics().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, rubricDBTypes, false, rubricPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Rubric struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Rubric: %s", err)
	}

	count, err = Rubrics().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
